POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1eCIsImlkIjoiNjY0MzkwMDIwZTM3MDk4YTE3NjYzZmIwIiwiaWF0IjoxNzE1NzA3MDk2LCJleHAiOjE3MTU3MTA2OTZ9.BuuvUnRMzlHgBzlwapVMvIrZHANsJPccpzEwAa02BoY

{
    "title": "Ludens is good",
    "url": "aboab.com",
    "likes": 77
}