POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1eCIsImlkIjoiNjY1ZjAwNjYzOGIyNzU4ZmFhM2M0MjkyIiwiaWF0IjoxNzE3NTAyMDY4LCJleHAiOjE3MTc1MDU2Njh9.zDT5ruVYn9PaofCP17B3K76lJj_2lSqs3aJd8JhZ5sM

{
    "title": "This is test 2",
    "author": "Tester",
    "url": "aboab.com",
    "likes": 72
}